### ISSUE TITLE
Recursively uncover 8 instead of 4 surrounding cells?

### ISSUE THREAD

**Issue by z-rui** [Hugozys/minesweeper#1]
https://github.com/Hugozys/minesweeper/blob/e9bd11ebe427f62b3ea30ceb6a5f29590cd47dfc/board.cpp#L205-L226
When uncovering a square which has no mines in the surrounding 8 squares, you should probably recursively uncover all the 8 (not 4) surrounding cells.
Maybe you can replace the repeated if statements with a loop, and avoid repeating the condition in the comment above each if statement.

**Comment by Hugozys** [comment]
Big thanks to Rui! I've updated the code for update function!.
